matrix:
  include:
    - language: node_js
      node_js: node
      before_script:
        - cd frontend
        - npm install
      script:
        - npm run lint
    - language: java
      jdk: openjdk11
      before_script:
        - cd backend
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script:
        - mvn test -B
