version: "3"
services:
  backend:
    build: backend/
    ports:
      - 5656:5656
    environment:
      NEO4J_HOST: "database"
      EXTERNAL_EXECUTABLE_PATH: "/app/executables/"
    depends_on:
      - database
  frontend:
    build: frontend/
    ports:
      - 8056:80
    volumes:
      - data:/app
    depends_on:
      - backend
  database:
    build: database/
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: "none"
    volumes:
      - data:/data
      - data:/logs
volumes:
  data:
