version: "3"
services:
  backend:
    build: backend/
    ports:
      - 5656:5656
    environment:
      NEO4J_HOST: "neo4j"
      REDIS_HOST: "redis"
  frontend:
    build: frontend/
    ports:
      - 8080:8080
    volumes:
      - data:/app
  neo4j:
    build: database/
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: "none"
    volumes:
      - data:/data
      - data:/logs
  redis:
    image: redis:alpine
    ports:
      - 6379
volumes:
  data:
